# Generated by Django 5.2.8 on 2025-11-15 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название продукта"),
                ),
                (
                    "model",
                    models.CharField(max_length=100, verbose_name="модель продукта"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="описание продукта"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(verbose_name="дата выхода продукта на рынок"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="название поставщика"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email поставщика"
                    ),
                ),
                (
                    "country",
                    models.CharField(max_length=255, verbose_name="страна поставщика"),
                ),
                (
                    "city",
                    models.CharField(max_length=255, verbose_name="город поставщика"),
                ),
                (
                    "street",
                    models.CharField(max_length=255, verbose_name="улица поставщика"),
                ),
                (
                    "house_number",
                    models.CharField(
                        max_length=255, verbose_name="номер дома поставщика"
                    ),
                ),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.CreateModel(
            name="ElectronicsNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="название сети"),
                ),
                (
                    "contacts_email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "contacts_country",
                    models.CharField(max_length=255, verbose_name="страна"),
                ),
                (
                    "contacts_city",
                    models.CharField(max_length=255, verbose_name="город"),
                ),
                (
                    "contacts_street",
                    models.CharField(max_length=255, verbose_name="улица"),
                ),
                (
                    "contacts_house_number",
                    models.CharField(max_length=255, verbose_name="номер дома"),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Factory"),
                            (1, "Retail Network"),
                            (2, "Individual Enterpreneur"),
                        ],
                        verbose_name="уровень иерархии сети",
                    ),
                ),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("products", models.ManyToManyField(to="electronics_network.product")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electronics_network.supplier",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Звено сети",
                "verbose_name_plural": "Звенья сети",
            },
        ),
    ]
