# Generated by Django 5.2.8 on 2025-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electronics_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="electronicsnetwork",
            name="contacts_email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
    ]
